theme: jekyll-theme-dinky
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - 404_templates.md
  - README.md
  - model_views.md
  - model_relationships.md
  - multi-modelforms_in_template.md
  - CONTRIBUTING.md
  - single-form-in-view-template.md
 
